export const library = {
  all: [
    "cat",
    "pants",
    "santa",
    "cool_glasses",
    "gloves",
    "boots",
    "blank_shirt",
    "sneakers",
  ],
  cat: {
    name: "Cat Ears",
    category: "Head",
    support: "wide",
    variants: [],
  },
  pants: {
    name: "Pants",
    category: "Pants",
    support: "wide",
    variants: [],
  },
  santa: {
    name: "Santa Hat",
    category: "Head",
    support: "wide",
    variants: [],
  },
  cool_glasses: {
    name: "Cool Glasses",
    category: "Head",
    support: "wide",
    variants: [],
  },
  gloves: {
    name: "Gloves",
    category: "Hands",
    support: "wide",
    variants: [],
  },
  boots: {
    name: "Boots",
    category: "Feet",
    support: "wide",
    variants: [],
  },
  blank_shirt: {
    name: "Blank T-Shirt",
    category: "Body",
    support: "wide",
    variants: [],
  },
  sneakers: {
    name: "Sneakers",
    category: "Feet",
    support: "wide",
    variants: [],
  },
};
